# Please use as example config for your own deployment
hostname: example.com
organization: "terrapak-dev"
storage: s3://my-modules-bucket 
secret: __SOME_RANDOM_STRING__
auth:
  type: github
  client_secret: __SECRET_KEY__
  client_id: __CLIENT_ID__
database:
  host: postgres.example.com
  username: __DB_USERNAME__
  password: __DB_PASSWORD__
redis:
  host: redis.example.com
  password: __PASSWORD__ 
github:
  appid: __APP_ID__
  keyfile: __KEY_FILE_PATH__
  webhook_secret: __WEBHOOK_SECRET__
