name: Publish Docker Image

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  buildAndPush:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract tag name
      id: extract_tag
      run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/terrapak:${{ steps.extract_tag.outputs.tag }}